// <auto-generated />
using FlaglerBookSwap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlaglerBookSwap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250405160502_UpdateUserIdToAutoIncrement")]
    partial class UpdateUserIdToAutoIncrement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlaglerBookSwap.Models.Courses", b =>
                {
                    b.Property<short>("course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("course_id"));

                    b.Property<string>("course_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("course_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FlaglerBookSwap.Models.Courses_Textbooks", b =>
                {
                    b.Property<byte>("unique_id")
                        .HasColumnType("tinyint");

                    b.Property<short>("course_id")
                        .HasColumnType("smallint");

                    b.Property<short>("textbook_id")
                        .HasColumnType("smallint");

                    b.HasKey("unique_id");

                    b.ToTable("Courses_Textbooks");
                });

            modelBuilder.Entity("FlaglerBookSwap.Models.Textbooks", b =>
                {
                    b.Property<short>("textbook_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("textbook_id"));

                    b.Property<string>("Authors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Book_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ISBN")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Publication_Year")
                        .HasColumnType("smallint");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("textbook_id");

                    b.ToTable("Textbooks");
                });

            modelBuilder.Entity("FlaglerBookSwap.Models.Users", b =>
                {
                    b.Property<short>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("UserID"));

                    b.Property<string>("date_created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("expected_grad_year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flagler_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
